sudo: required
language: C++

matrix:

  include:

  - env: PG=9.3/2.3
    addons:
      postgresql: 9.3
      apt:
        packages:
        - postgresql-9.3
        - postgresql-9.3-pgtap
        - postgresql-server-dev-9.3
        - postgresql-9.3-postgis-2.3

  - env: PG=9.4/2.3
    addons:
      postgresql: 9.4
      apt:
        packages:
        - postgresql-9.4
        - postgresql-9.4-pgtap
        - postgresql-server-dev-9.4
        - postgresql-9.4-postgis-2.3

  - env: PG=9.5/2.3
    addons:
      postgresql: 9.5
      apt:
        packages:
        - postgresql-9.5
        - postgresql-9.5-pgtap
        - postgresql-server-dev-9.5
        - postgresql-9.5-postgis-2.3

  - env: PG=9.6/2.3
    addons:
      postgresql: 9.6
      apt:
        packages:
        - postgresql-9.6
        - postgresql-9.6-pgtap
        - postgresql-server-dev-9.6
        - postgresql-9.6-postgis-2.3

before_install:
  # Install common packages
  - sudo apt-get -qq update
  - sudo apt-get install -y pgtap
    debhelper fakeroot
  # Show some build info
  - apt-cache search postgis
  - echo $PATH
  - which pg_config
  - pg_config --version
  - psql --version
  - psql -c 'select version()'
  - find `pg_config --pkglibdir`| grep postgis
  # Enable fetching packages from packagecloud
  # test and production repositories
  - curl -s https://packagecloud.io/install/repositories/linz/test/script.deb.sh | sudo bash
  - curl -s https://packagecloud.io/install/repositories/linz/prod/script.deb.sh | sudo bash
  # Install dbpatch
  - sudo apt-get install postgresql-`echo $PG | cut -d/ -f1`-dbpatch
  # Install table_version
  - sudo apt-cache search tableversion
  - sudo apt-get install postgresql-`echo $PG | cut -d/ -f1`-tableversion
script:
  - make
  - make check || { cat regression.diffs; false; }
  - sudo env "PATH=$PATH" make install
  - make installcheck
  # Test build and installation of debian package
  - make deb
  - sudo dpkg -i ../linz-bde-schema*.deb
