sudo: false
language: C++
services:
  - postgresql
addons:
  apt:
    packages:
    - postgresql-9.6
    - postgresql-9.6-pgtap
    - postgresql-server-dev-9.6
script:
  - make
  - make check || { cat regression.diffs; false; }
