#!/bin/sh

DB_NAME=
export SKIP_INDEXES=no
export ADD_REVISIONS=no
export PSQL=psql
export SCRIPTSDIR=/usr/share/linz-bde-schema/sql/

if test -n "${BDESCHEMA_SQLDIR}"; then
    SCRIPTSDIR=${BDESCHEMA_SQLDIR}
fi

if test ! -f "${SCRIPTSDIR}/02-bde_schema.sql"; then
    cat >&2 <<EOF
Cannot find 02-bde_schema.sql in ${SCRIPTSDIR}
Please set LDSBDESCHEMA_SQLDIR environment variable
EOF
    exit 1
fi

while test -n "$1"; do
    if test $1 = "--noindexes"; then
        SKIP_INDEXES=yes
        shift; continue
    elif test $1 = "--revision"; then
        ADD_REVISIONS=yes
        shift; continue
    else
        DB_NAME=$1; shift
    fi
done

if test -z "$DB_NAME"; then
    echo "Usage: $0 [--noindexes] [--revision] <database>" >&2
    exit 1
fi

export PGDATABASE=$DB_NAME
(
cat << EOF
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS _patches;
CREATE EXTENSION IF NOT EXISTS dbpatch SCHEMA _patches;
EOF

for file in ${SCRIPTSDIR}/*.sql; do
    if test ${SKIP_INDEXES} = 'yes' &&
       `basename $file .sql` = '04-bde_schema_index';
    then
        continue
    fi
    cat ${file}
done

if test "${ADD_REVISIONS}" = "yes"; then
    echo 'CREATE EXTENSION IF NOT EXISTS table_version;'
    file=${SCRIPTSDIR}/versioning/01-version_tables.sql
    cat ${file} || exit 1
fi

) | $PSQL -tA --set ON_ERROR_STOP=1
