#!/usr/bin/perl

# Usage: dict2comment.pl lds-full-landonline-data-dictionary-and-models.txt
# NOTE: lds-full-landonline-data-dictionary-and-models.txt is expected
# to be generated by links -dump against the output of pdf2htmlEX on
# lds-full-landonline-data-dictionary-and-models.pdf

use strict;

my $state = 0;
my %ent;
my $desc;
my %tableNameMap;

while(my $l = <DATA>) {
  chop($l);
  $l = lc($l);
  my ($n,$tn) = split(':', $l);
  #print STDERR "MAP: $n => $tn\n";
  $tableNameMap{$n} = $tn;
}

sub name2tablename
{
    my $name = shift;
    my $tablename = lc($name);
    $tablename =~ s/^\s*//;
    $tablename =~ s/\s*$//;
    $tablename =~ s/ /_/g;
    if ( $tableNameMap{$tablename} )
    {
        #print STDERR "Found MAP: $tablename => $tableNameMap{$tablename}\n";
        $tablename = $tableNameMap{$tablename};
    }
    else
    {
        #print STDERR "Not Found MAP: $tablename\n";
        $tablename = 'bde.crs_' . $tablename;
    }
    return $tablename;
}

print "-- Generated by $0 on " . `date` . "\n";
while (<>)
{
    #if ( $state == 0 && /^\s*3\.[0-9]* *([^\(]*) *\(([^\)]*)\)/ )
    if ( $state == 0 && /govt\.nz\/(table|layer)\/.*\)$/ )
    {
        my $line = $_;
        #print STDERR "-- LINE $line\n";
        $line =~ s/^\s*3\.[0-9]* *//;
        #print STDERR "-- LINE $line\n";
        $line =~ /^([^\(]*) *\(([^\)]*)\)/;
        $state = 1;
        $ent{'name'} = name2tablename($1);
        $ent{'url'} = $2;
        $ent{'name'} =~ s/\s*$//;
        $ent{'name'} =~ s/\s/_/g;
        #print STDERR "-- Found 3 - [$ent{'name'}], [$ent{'url'}]\n";
        next;
    }

    if ( $state == 1 && /Description:/ )
    {
        #print STDERR "-- Found Description\n";
        $state = 2;
        $desc = '';
        next;
    }

    if ( $state == 2 )
    {
        if ( /Data element/ )
        {
            $state = 0;
            #print STDERR "-- Found Data element\n";
            # Add a blank line after first sentence, if there are
            # multiple sentences
            $desc =~ s/\. */.\n\n/ if $desc =~ m/\..*\./;
            $ent{'desc'} = $desc;
            next unless $ent{'name'} =~ m/bde\./;
            print <<EOF;
COMMENT ON TABLE $ent{'name'} IS \$DESC\$
$ent{'desc'}

$ent{'url'}
\$DESC\$;

EOF
        }
        else
        {
            my $line = $_;
            #print "GOT: [$line]\n";
            $line =~ s/^\s*//;
            $line =~ s/\s*$//;
            #print STDERR "GOT chopped: [$line]\n";
            next if $line =~ /^\s*Page \|/;
            next if $line =~ m/^\s*$/;
            $desc .= ' ' if $desc;
            $desc .= $line;
            #print STDERR "DESC: [$desc]\n";
        }
    }
}

# Following are the known mappings between names in document
# and table names
__END__
Adjustment_Coefficient:bde.crs_adjust_coef
Adjustment_Method:bde.crs_adjust_method
Adjustment_User_Coefficient:bde.crs_adj_user_coef
Affected_Parcel:bde.crs_affected_parcl
Coordinate_Order:bde.crs_cord_order
Coordinate_Precision:bde.crs_cor_precision
Coordinate_System:bde.crs_coordinate_sys
Coordinate_Type:bde.crs_coordinate_tpe
Electorate_Place:bde.crs_elect_place
encumbrance_share:bde.crs_enc_share
Feature_Name_Point:bde_ext.feature_name_pt
Feature_Name_Polygon:bde_ext.feature_name_poly
Legal_Description:bde.crs_legal_desc
Legal_Description_Parcel:bde.crs_legal_desc_prl
mark_physical_state:bde.crs_mrk_phys_state
mark_supporting_document:bde.crs_mark_sup_doc
node_proposed_order:bde.crs_node_prp_order
observation_accuracy:bde.crs_obs_accuracy
observation_element_type:bde.crs_obs_elem_type
Observation_Set:bde.crs_obs_set
Observation_Type:bde.crs_obs_type
Official_Coordinate_System:bde.crs_off_cord_sys
Parcel_Linestring:bde_ext.parcel_ls
Parcel_Boundary:bde.crs_parcel_bndry
Parcel_Dimension:bde.crs_parcel_dimen
Reduction_Method:bde.crs_reduct_meth
Reduction_Run:bde.crs_reduct_run
Reference_Survey:bde.crs_ref_survey
Road_Centre_Line:bde.crs_road_ctr_line
Road_Name_Association:bde.crs_road_name_asc
Statistical_Area:bde.crs_statist_area
Statistical_Version:bde.crs_stat_version
Statutory_Action_Parcel:bde.crs_stat_act_parcl
Survey_Admin_Area:bde.crs_sur_admin_area
Survey_Plan_Image_Revision:bde_ext.survey_plan_image_revision
Survey_Plan_Reference:bde.crs_sur_plan_ref
System_Code:bde.crs_sys_code
System_Code_Group:bde.crs_sys_code_group
Title_Document_Reference:bde.crs_title_doc_ref
Title_Encumbrance:bde.crs_ttl_enc
Title_Hierarchy:bde.crs_ttl_hierarchy
Title_Instrument:bde.crs_ttl_inst
Title_Instrument_Title:bde.crs_ttl_inst_title
Title_Memorial_Text:bde.crs_title_mem_text
Title_Parcel_Association:bde.cbe_Title_Parcel_Association
Transaction_Type:bde.crs_transact_type
Unit_Of_Measure:bde.crs_unit_of_meas
Vector_Point:bde_ext.vector_pt
