#!/bin/sh

#
# Generate table comments from DataDictionary XML
# See
# https://github.com/linz/linz-bde-schema/issues/54#issuecomment-347681119
#

test -n "$1" || {
    echo "Usage: $0 <DataDictionary.xml>" >&2 && exit 1;
}

SOURCE=$1

echo "-- Generated by $0 on "`date`
echo

xsltproc /dev/stdin $SOURCE << EOF

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:output method="text"/>
  <xsl:template match="entity-list">
    <xsl:for-each select="entity">
      <xsl:if test="contains(code, 'CRS_')">
          <xsl:text>COMMENT ON TABLE bde.</xsl:text>
          <xsl:value-of select="code"/>
          <xsl:text> IS \$DESC\$
    </xsl:text>
          <xsl:value-of select="description"/>
          <xsl:text>
\$DESC\$;

</xsl:text>
      </xsl:if>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
EOF
