name: Test

on:
    push:
        branches:
            - master
            - packagecloud
            - 'release-*'
        tags-ignore:
            - 'debian/*'
            - '*-start'
    pull_request:
        branches:
            - '*'
    schedule:
        - cron: '0 12 * * 0'

jobs:
    lint:
        runs-on: ubuntu-20.04

        steps:
            - name: Check out repository
              uses: actions/checkout@v2.4.0

            - name: Install Dependencies
              run: sudo snap install --classic pre-commit

            - name: Run pre-commit hooks
              run: pre-commit run --all-files

    test:
        name: PostgreSQL ${{ matrix.pg }}, PostGIS ${{ matrix.pgis }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                # Combines <https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS> and
                # `curl https://apt.postgresql.org/pub/repos/apt/dists/bionic-pgdg/main/binary-amd64/Packages | grep --only-matching '^Package: postgresql-[0-9.]\+-postgis-[0-9.]\+$' | sort --version-sort`.
                include:
                    - os: ubuntu-18.04
                      pg: '10'
                      pgis: '2.4'
                    - os: ubuntu-18.04
                      pg: '10'
                      pgis: '2.5'
                    - os: ubuntu-18.04
                      pg: '10'
                      pgis: '3'
                    - os: ubuntu-18.04
                      pg: '12'
                      pgis: '2.5'
                    - os: ubuntu-18.04
                      pg: '12'
                      pgis: '3'
        env:
            # Set PATH as postgresql-server-dev-all pretends version is 11
            PATH: /usr/lib/postgresql/${{ matrix.pg }}/bin:/bin:/usr/bin:/usr/local/bin
            # Make apt non-interactive by default, and not showing progress
            APT: 'apt-get -o Dpkg::Progress=0 -o Dpkg::Use-Pty=0'
            # Avoid warnings on apt-key usage
            APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1
            DBPATCH_BRANCH: 'master'
            TABLEVERSION_BRANCH: 'master'

        steps:
            - name: Check out repository
              uses: actions/checkout@v2.4.0
              with:
                  fetch-depth: 0

            - name: Purge other software
              run:
                  sudo ${APT} purge libpq5 libpq-dev *php* postgresql postgresql-client-common
                  postgresql-common

            - name: Remove existing PostgreSQL libraries
              run: sudo rm --force --recursive --verbose /var/lib/postgresql

            - name: Install build dependencies
              run: |
                  sudo ${APT} update
                  sudo ${APT} install curl ca-certificates gnupg

            - id: distro
              run: echo "::set-output name=codename::$(lsb_release -cs)"

            - name: Enable fetching packages from apt.postgresql repository
              run: |
                  curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
                  echo "deb http://apt.postgresql.org/pub/repos/apt/ ${{ steps.distro.outputs.codename }}-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list

            - name: Enable fetching packages from packagecloud test repository
              run: |
                  curl -Ls https://packagecloud.io/linz/test/gpgkey | sudo apt-key add -
                  echo "deb https://packagecloud.io/linz/test/ubuntu/ ${{ steps.distro.outputs.codename }} main" | sudo tee /etc/apt/sources.list.d/linz-test.list

            - name: Enable fetching packages from packagecloud prod repository
              run: |
                  curl -Ls https://packagecloud.io/linz/prod/gpgkey | sudo apt-key add -
                  echo "deb https://packagecloud.io/linz/prod/ubuntu/ ${{ steps.distro.outputs.codename }} main" | sudo tee /etc/apt/sources.list.d/linz-prod.list

            - name: Install dependencies
              run: |
                  sudo ${APT} -qq update
                  sudo ${APT} -qq install \
                      debhelper \
                      fakeroot \
                      postgresql-client-${{ matrix.pg }} \
                      postgresql-${{ matrix.pg }} \
                      postgresql-${{ matrix.pg }}-pgtap \
                      postgresql-${{ matrix.pg }}-postgis-${{ matrix.pgis }} \
                      postgresql-${{ matrix.pg }}-postgis-${{ matrix.pgis }}-scripts \
                      postgresql-server-dev-${{ matrix.pg }} \
                      postgresql-${{ matrix.pg }}-tableversion \
                      tableversion \
                      postgresql-${{ matrix.pg }}-dbpatch \
                      dbpatch

            - name: Install dbpatch PostgreSQL extension
              run: |
                  pushd /tmp
                  wget -q -O - \
                      https://github.com/linz/postgresql-dbpatch/archive/${{env.DBPATCH_BRANCH}}.tar.gz \
                      | tar xzf -
                  cd postgresql-dbpatch-${{env.DBPATCH_BRANCH}}
                  sudo -E make install
                  popd

            - name: Install table_version PostgreSQL extension
              run: |
                  pushd /tmp
                  wget -q -O - \
                      https://github.com/linz/postgresql-tableversion/archive/${{env.TABLEVERSION_BRANCH}}.tar.gz \
                      | tar vxzf -
                  cd postgresql-tableversion-${{env.TABLEVERSION_BRANCH}}
                  sudo -E make install
                  popd

            - name: Setup PostgreSQL user
              run: |
                  sudo -u postgres createuser -s "$USER"
                  sudo -u postgres createuser -s root

            - name: Build
              run: |
                  # Build
                  make

            - name: Test build
              run: |
                  # Pre-install tests
                  make check

            - name: Install
              run: |
                  sudo -E make install

            - name: Test installation
              run: |
                  # Post-install tests
                  make installcheck
                  make check-loader-stdout

            - name: Test upgrades
              run: |
                  # Test upgrades
                  test/test-upgrades.bash

            - name: Test packaging
              run: |
                  make deb
                  # Building this package requires dbpatch and tableversion
                  sudo apt-get install dbpatch tableversion
                  sudo dpkg -i ../linz-bde-schema*.deb

            - name: Test publication
              run: |
                  make check-publisher
              if: matrix.pg >= 10

    package:
        needs: test
        name: Package for Debian
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                distro: [bionic, focal]
        steps:
            - name: Check out repository
              uses: actions/checkout@v2.4.0
              with:
                  fetch-depth: 0

            - name: Determine packagecloud publication target
              run: |
                  # TODO: it would be nice to turn this into a single-liner in
                  #       github-action syntax
                  echo "GitHub ref: ${{ github.ref }}"
                  echo "GitHub event_name: ${{ github.event_name }}"
                  REPO=
                  if test "${{ github.event_name }}" = 'push'; then
                    if expr "${{ github.ref }}" : "refs/tags/" > /dev/null; then
                      REPO=test
                      git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
                    elif test "${{ github.ref }}" = 'refs/heads/packagecloud' \
                           -o "${{ github.ref }}" = 'refs/heads/master'
                    then
                      REPO=dev
                    fi
                  fi
                  echo "REPO=$REPO" | tee -a $GITHUB_ENV

            - name: Build and upload to Packagecloud
              uses: linz/linz-software-repository@v8
              with:
                  release: ${{ matrix.distro }}
                  packagecloud_token: ${{ secrets.LINZCI_PACKAGECLOUD_TOKEN }}
                  packagecloud_repository: ${{ env.REPO }}
